---
- include_tasks: "preflight.yml"

- name: "Deploy pushsafer-webhook service file"
  template:
    src: "pushsafer-webhook.service.j2"
    dest: "/etc/systemd/system/pushsafer-webhook.service"
  notify: "Restart pushsafer_webhook"

- name: "Deploy pushsafer-webhook config file"
  template:
    src: "pushsafer_alertmanager_webhook.conf.j2"
    dest: "{{ pushsafer_webhook_docker__data_dir }}/etc/pushsafer_alertmanager_webhook.conf"
    owner: "{{ pushsafer_webhook_docker__system_user }}"
    group: "{{ pushsafer_webhook_docker__system_group }}"
    mode: 0640
  notify: "Restart pushsafer_webhook"
